### PR TITLE
fix: specify framerate in constraints

### PR DESCRIPTION
**Pull request by kittykel**
change minimum framerate to match chosen value in order to stop unnecessary frame drops on wayland (demo video attached)
especially relevant when streaming videos from a web browser
i've seen at least one other person mentioning what i believe to be this bug in the support channel on discord

this may also fix frame drops i've experienced on X11 when streaming games but i haven't tested 

discord is @puppyears if u need to ask me a question i honestly don't use github and am unfamiliar with this api, i just noticed a problem that bothered me so i tried to fix it

probably relevant information:
nvidia-dkms 555.58-1
kde plasma 6.1.1-1

https://github.com/Vencord/Vesktop/assets/95729061/3b1876b3-ffef-413c-9d08-8915802a3283

### CODE REVIEW

**Comment by PolisanTheEasyNick** [comment]
Thank you for finding!
But you need also change it here: https://github.com/Vencord/Vesktop/blob/main/src%2Frenderer%2Fcomponents%2FScreenSharePicker.tsx#L724

**Comment by kittykel** [comment]
> Thank you for finding! But you need also change it here: https://github.com/Vencord/Vesktop/blob/main/src%2Frenderer%2Fcomponents%2FScreenSharePicker.tsx#L724

done, thank you <3

**Comment by aaomidi** [comment]
This seems fine to merge?

**Comment by Vendicated** [comment]
thanks!

**Comment by NoyingNabi** [comment]
Has this been merged into 1.5.3? If yes that did not fix it for me. Am I missing something?

**Comment by PolisanTheEasyNick** [comment]
> If yes that did not fix it for me. Am I missing something?

Maybe you encountering #629?

**Pull request merged**
