### PR TITLE
feat: use standardized icon for macOS

### PR DESCRIPTION
**Pull request by ryanccn**
Designed using Apple's official Sketch design template.

### CODE REVIEW

**Comment by Vendicated** [comment]
what's the difference?

**Comment by ryanccn** [comment]
@Vendicated it uses the rounded square icon format that has been the standard from Big Sur onwards

**Comment by Vendicated** [comment]
please show a screenshot

**Comment by ryanccn** [comment]
CleanShot 2023-07-09 at 17 11 32@2x

**Comment by Vendicated** [comment]
This code doesn't seem right. You removed the setDock line and MACOS_ICON_PATH seems unused

**Comment by ryanccn** [comment]
Yeah that constant can probably be removed, you don’t need a `setIcon` call on macOS

**Comment by Vendicated** [comment]
i think the static icon shouldnt be needed anymore?

i also think this icon would also apply to other platforms, so maybe rename the file to build/icon.macos.icns and specify in package.json electron-builder config

**Comment by ryanccn** [comment]
> i think the static icon shouldnt be needed anymore?

yes, I'll remove that

> i also think this icon would also apply to other platforms, so maybe rename the file to build/icon.macos.icns and specify in package.json electron-builder config

it wouldn't, icns is a macOS-specific format

**Comment by Vendicated** [comment]
> i also think this icon would also apply to other platform

image

**Comment by Vendicated** [comment]
WRONG BUTTON

**Comment by Vendicated** [comment]
thank u btw

**Pull request merged**
