### PR TITLE
Update Dependencies; Electron v32

### PR DESCRIPTION
**Pull request by IlChitarrista**
Updates all dependencies to the latest version, mostly includes Electron v32 which should have improved the screensharing situation when using Pipewire on Linux.

Related: [PipeWire capturer: fix some possible threading issues](https://webrtc.googlesource.com/src.git/+/06e88bbb5aabdbc2614e51739d79a756c9e4d34b) which is included in Chromium M127, Electron v32 ships with M128
Related: https://github.com/Vencord/Vesktop/issues/629

I personally haven't seen a significant difference on GNOME 47.beta but I haven't tested KDE where this issue seemed more prominent.

### CODE REVIEW

**Comment by tsuza** [comment]
A friend of mine has been running electron 32 since before it became stable, and they haven't had any issues. 
I tried it for a brief period and I didn't run against any issues either.

**Comment by tsuza** [comment]
Any updates on merging this? It has been over 3 weeks.

**Comment by IlChitarrista** [comment]
> Any updates on merging this? It has been over 3 weeks. People are manually running Vesktop on Electron 32/33 and they haven't run into a single issue, so it shouldn't have any breaking changes.

The MR is ready, although perhaps https://github.com/Vencord/Vesktop/pull/859 should be merged first.
@Vendicated, can you review this?

**Comment by IlChitarrista** [comment]
Fixed by 37db07807a62435b99a6a11037c84184517ebc69

**Pull request closed without merging**
