### PR TITLE
Vennie splash

### PR DESCRIPTION
**Pull request by TheKodeToad**
Epic PR

credit to shoritsu (probably should wait for permission ig?)

### CODE REVIEW

**Comment by ZirixCZ** [comment]
This could be fixed by https://github.com/Vencord/Vesktop/pull/355 with keeping shiggy as the default

**Review by Sqaaakoi — CHANGES_REQUESTED** [review]
i wouldn't replace shiggy entirely, instead i would make it randomly pick shiggy or vennie

**Comment by TheKodeToad** [comment]
Shiggy was just used without permission so I don't think it should stay in Vesktop and Vencord - we have no rights to use it (ig an emoji is a bit different though)

**Comment by lewisakura** [comment]
Was permission granted?

**Comment by Vendicated** [comment]
closing in favour of custom assets

**Pull request closed without merging**
