### PR TITLE
Allow for higher stream FPS

### PR DESCRIPTION
**Pull request by Grafaffel**
Allow for higher stream FPS in the Picker

### CODE REVIEW

**Comment by PolisanTheEasyNick** [comment]
Discord will not allow streaming more than 60 FPS

**Comment by kaitlynkittyy** [comment]
I second that, ive tried and to no avail, but even then the bitrate barely holds 1080p60 stable, 1440 is really rough on it, so even 480p120 would be really tough.

**Comment by Grafaffel** [comment]
how does `FakeNitor` does it then?

**Comment by Grafaffel** [comment]
I saw a custom plugin in the Vencord server by someone, wich would allow for higher fps streaming. He showed it in a VC, and is was silky smoooth

**Comment by PolisanTheEasyNick** [comment]
I applied 120 fps at Track settings, and we still are hardcapped to 60 fps, even when sometimes we reach for moment >60 fps
image
Also, we have strange bitrate behavior.

**Comment by Grafaffel** [comment]
I found the plugin now: [Better Screenshare](https://github.com/philhk/Vencord/tree/better-plugins/src/plugins/betterScreenshare.desktop)

**Comment by lewisakura** [comment]
There is no purpose if it doesn't actually increase the framerate, as indicated by some people in this post

**Comment by Grafaffel** [comment]
> There is no purpose if it doesn't actually increase the framerate, as indicated by some people in this post

ok, I'm closing the issue now

**Pull request closed without merging**
