### PR TITLE
Force disable automatic gain control

### PR DESCRIPTION
**Pull request by Justus0405**
This code forcefully disables automatic gain control, a feature that adjusts microphone volume system-wide, even in Windows when apps are denied permission to change microphone settings. The code was developed by Joey Watts and is licensed under the MIT License, I've been using it for two weeks, and it works perfectly.

### CODE REVIEW

**Comment by Justus0405** [comment]
fixes #161

**Comment by Justus0405** [comment]
Also confirmed to be an issue on Linux

**Comment by Vendicated** [comment]
it's not a good idea to **force** disable something that people might want enabled. it should be tied to the autogain switch discord has

**Comment by Novantric** [comment]
Make it a plugin?

**Comment by thibaultmol** [comment]
Please make this an easy-to-enable thing.
It's so frustrating when your friends ask every five minutes why you're so quiet (and it turns out that it was adjusting your mic volumes once again)

**Pull request closed without merging**
