### PR TITLE
add linux audio screensharing

### PR DESCRIPTION
**Pull request by Vendicated**
Adds audio screenshare on linux via pipewire

Allows you to choose to share either your entire system audio (without Discord), or a specific application

## TODO
- [x] kill virtmic once stream is stopped

## Needs testing
- [x] Behaves correctly on pulseaudio. That is: does not crash; displays "failed to retrieve audio sources"
- [x] works on fedora
- [x] works on ubuntu
- [ ] works on steamos
- [x] works for sharing audio of individual apps
- [x] works for sharing system audio without including discord itself

resolves https://github.com/Vencord/Vesktop/issues/117

### CODE REVIEW

**Comment by uku3lig** [comment]
Doesn't work on wayland, the XDG portal window picker opens just fine and allows to select a window but then the vencord picker is empty:
image

In addition, pipewire seems to error after selecting something in the portal picker: `'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()`

(Tested both on Hyprland 0.30.0 and GNOME 44.4)

**Comment by Vendicated** [comment]
yes

**Comment by kaitlynkittyy** [comment]
> Doesn't work on wayland, the XDG portal window picker opens just fine and allows to select a window but then the vencord picker is empty: image
> 
> In addition, pipewire seems to error after selecting something in the portal picker: `'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()`
> 
> Also after canceling clicking on the Go Live button again doesn't do anything, without anything being output in the logs and when closed exists with a SIGSEGV.
> 
> (Tested both on Hyprland 0.30.0 and GNOME 44.4)

Try my fork, wayland-fixes branch.
Most of those issues should be resolved

**Comment by uku3lig** [comment]
> Try my fork, wayland-fixes branch. Most of those issues should be resolved

this seems to be working fine, except for one little issue: electron 26 turns the app into a white screen a few seconds after launch, as described in #125. works fine on electron 25.8.2

**Comment by Vendicated** [comment]
these issues should now all be fixed (including the electron 26 whitescreen)

___

> Instead of the virtmic binary you could try to use [kakxem/node-pipewire](https://github.com/kakxem/node-pipewire), that may be a bit cleaner than bundling a prebuilt binary.

Curve is helping us turn it into a native addon instead. thanks though!

**Comment by Vendicated** [comment]
> besides the thing with the screen sharing portal popping up multiple times

yeah, it's sadly still an issue even after all these fixes. The first time it requests is normal, and it calls our electron registered handler. then right before it starts streaming, it asks again, this time without triggering the electron handler

> on a random website

so it happens on any website, not just discord?

**Comment by Vendicated** [comment]
what chromium version are you using? the site you linked works correctly for me on `Version 117.0.5938.149 (Official Build, ungoogled-chromium) (64-bit)`

**Comment by Vendicated** [comment]
i just installed chrome and it works fine for me on `Version 118.0.5993.70 (Official Build) (64-bit)` (fedora)

here's a recording, in case i'm misunderstanding

[Screencast from 2023-10-12 00-17-14.webm](https://github.com/Vencord/Vesktop/assets/45497981/4a4c99b6-110d-445d-bc4a-cc668d355c62)

**Comment by Vendicated** [comment]
maybe it's an issue with pipewire itself or whichever DE/WM you use?
Here's mine:
```
gnome 44.5

pipewire
Compiled with libpipewire 0.3.81
Linked with libpipewire 0.3.81
```

**Comment by Vendicated** [comment]
i just installed kde and can't repro

https://github.com/Vencord/Vesktop/assets/45497981/429e8354-7e6a-44ae-b404-d65e02e4d453

**Comment by Vendicated** [comment]
now migrated to curve's addon. if you would like to test this, clone and build his fork https://github.com/Curve/linux-virtmic/ in the same directory your Vesktop clone is in. see [my note on compiling](https://github.com/Vencord/linux-virtmic/pull/3#issuecomment-1758708189)

**Comment by D3SOX** [comment]
image

There seems to be a problem when there are multiple outputs by the same application but other than that it works fine for me

**Comment by Curve** [comment]
> image
> 
> There seems to be a problem when there are multiple outputs by the same application but other than that it works fine for me

Oh, good catch, will return a `set` instead of vector

**Comment by FlashOnFire** [comment]
Also tried on Arch and got this message after choosing what to share :
image
Along with this error : 
image

Screensharing (without audio) is working though

(Tested on Hyprland 0.30.0 and i3 4.22)

**Comment by Curve** [comment]
> Also tried on Arch and got this message after choosing what to share : image Along with this error : image
> 
> Screensharing (without audio) is working though
> 
> (Tested on Hyprland 0.30.0 and i3 4.22)

This probably happens because the virtmic code was updated and this PR is not yet updated

**Comment by uku3lig** [comment]
everything seems to be working fine with last commit :+1:

**Comment by FlashOnFire** [comment]
Same for me :+1:

**Comment by Vendicated** [comment]
This pr is now very close to being done and you no longer need to build virtmic/venmic yourself

One thing that still needs to be tested is that it behaves correctly on pulseaudio. That is:
- does not segfault/crash
- displays "Failed to retrieve Audio Sources. If you would like to stream with Audio, make sure you're using Pipewire, not Pulseaudio"

**Comment by D3SOX** [comment]
It works for fine for me
image

**Comment by D3SOX** [comment]
I just noticed this always exists after the audio selection input was shown once. Can't it be killed when no stream is running?
image

**Comment by Curve** [comment]
> I just noticed this always exists after the audio selection input was shown once. Can't it be killed when no stream is running?
> image
> 

Recreating the virtual device would be absolutely unnecessary imho but could be added

**Comment by uku3lig** [comment]
it seems that applications using pipewire-alsa are not detected (or at least don't show up in the audio selection menu), see attached screenshot

image

**Comment by Curve** [comment]
> it seems that applications using pipewire-alsa are not detected (or at least don't show up in the audio selection menu), see attached screenshot (tested on pipewire `0.3.82`, the two apps shown are [osu-lazer](https://github.com/ppy/osu) launched with `SDL_VIDEODRIVER=wayland` and [uku3lig/csf-reader](https://github.com/uku3lig/csf-reader))
> 
> image
> 

Currently only applications that contain sole props are shown (namely application.process.id, application.process.binary and node.name).

Could you please send in the output of `pw-dump` while OSU is playing audio?

We might need to give the client control over which props he requires to be included

**Comment by Curve** [comment]
> > [~snip](https://github.com/Vencord/Vesktop/pull/130#issuecomment-1771326427)
> 
> @uku3lig 
> 
> Currently only applications that contain certain props are shown (namely application.process.id, application.process.binary and node.name).
> 
> Could you please send in the output of `pw-dump` while OSU is playing audio?
> 
> We might need to give the client control over which props he requires to be included (maybe an option similar to "Show all processes")

The output is probably going to be pretty big or may contain some personal info (username, and so on)

If you want to you can also DM me the output on discord: @curve.cpp

**Comment by wearrrrr** [comment]
Just tested and it works flawlessly :+1:, both app and entire system audio work. :D

**Comment by milena-kos** [comment]
works good on ubuntu

**Comment by Vendicated** [comment]
hi @uku3lig, could you try again now and see if your issue is fixed?

**Comment by uku3lig** [comment]
works flawlessly, thank you very much!

**Comment by afrozenpeach** [comment]
Vencord claims it can't retrieve my sound sources and says to use pipewire, but I'm definitely using pipewire. Here's a pw-dump output from my system. 

[pwdump.txt](https://github.com/Vencord/Vesktop/files/13173153/pwdump.txt)

**Comment by Vendicated** [comment]
probably related to using older glibc++. will be fixed once we publish our flatpak soon (and if you use that)

please don't necro closed prs in the future, instead make a new issue!

**Comment by leo60228** [comment]
This might be a fairly niche usecase, but would it be possible to have a way to select a real audio input for screensharing? My usecase for this is streaming from a game console where my capture solution only handles video, so I just connect the console's audio output to my motherboard's line in jack.

**Comment by Curve** [comment]
> This might be a fairly niche usecase, but would it be possible to have a way to select a real audio input for screensharing? My usecase for this is streaming from a game console where my capture solution only handles video, so I just connect the console's audio output to my motherboard's line in jack.

Venmic allows this, it would have to be utilized by vencord but that should be fairly easy

**Comment by Vendicated** [comment]
Screenshot_2023-11-08-23-31-55-93_4d38fce200f96aeac5e860e739312e76

**Pull request merged**
