### PR TITLE
Make linux display badges

### PR DESCRIPTION
**Pull request by patyhank**
Add `desktopName` to package.json to make badge visible
https://github.com/signalapp/Signal-Desktop/issues/3387#issuecomment-500109546

### CODE REVIEW

**Comment by D3SOX** [comment]
Not sure if this is always correct because the AUR package uses `vencord.desktop`

**Comment by nyakowint** [comment]
I dont think the aur package is official

**Comment by D3SOX** [comment]
Hm, it's mentioned in the README. I also don't get why it even includes its own desktop file. Isn't there a pacman target for electron-builder that could be used to bring it more in line with the other packages?

**Comment by uku3lig** [comment]
> I also don't get why it even includes its own desktop file.

aur maintainers are built different

jokes aside, it uses `pnpm package:dir`, which doesn't output a `.desktop` file

**Comment by patyhank** [comment]
On Linux platform, only supports Unity desktop environment, you need to specify the *.desktop file name to desktopName field in package.json. By default, it will assume {app.name}.desktop.
And this only seems to affect Linux.

**Comment by Vendicated** [comment]
this does nothing for me

**Pull request closed without merging**
