### PR TITLE
Remove `transparent: true` for transparencyOption

### PR DESCRIPTION
**Pull request by Marocco2**
See https://github.com/electron/electron/issues/29937#issuecomment-1193030133

### CODE REVIEW

**Comment by Marocco2** [comment]
Waiting for https://github.com/electron/electron/pull/40749 to be merged

**Comment by Vendicated** [comment]
why are we waiting for that issue? according to the first link it should already work, no?

**Comment by Marocco2** [comment]
> why are we waiting for that pr? according to the first link it should already work, no?

Because it doesn't work and glitches out (background will become black and there is heavy ghosting on UI elements)

**Comment by Vendicated** [comment]
thanks! please fix ci

**Comment by Vendicated** [comment]
you know you can just run autofix, riiight...

**Comment by Marocco2** [comment]
> you know you can just run autofix, riiight...

Sorry about that. I repeated `pnpm test` on my end but it was throwing thousands of CR errors because I'm on Windows 😓

Thanks for autofixing for me

**Pull request merged**
